# SwiftLint Configuration for TTRPGCharacterSheets
# Strict configuration for production-quality iOS app

# Paths to include for linting
included:
  - TTRPGCharacterSheets

# Paths to exclude from linting
excluded:
  - Pods
  - .build
  - .swiftpm
  - DerivedData
  - vendor
  - Carthage
  - build
  - .git

# Analyzer rules (run with --analyze flag)
analyzer_rules:
  - unused_declaration
  - unused_import

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules (too strict or not applicable)
disabled_rules:
  - todo # Allow TODO comments during development
  - blanket_disable_command # Allow selective SwiftLint disabling

# Custom rule configurations

# Line length
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# File length
file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Function parameter count
function_parameter_count:
  warning: 5
  error: 8

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Nesting depth
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Identifier naming
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    - db
    - to
    - on
    - at
  validates_start_with_lowercase: true

# Type name
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 60
  validates_start_with_lowercase: false
  excluded:
    - ID
    - URL

# Large tuples
large_tuple:
  warning: 3
  error: 4

# Number of trailing whitespace characters
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

# Trailing comma in arrays and dictionaries
trailing_comma:
  mandatory_comma: true

# Force unwrapping (allow with caution)
force_unwrapping:
  severity: warning

# Force cast (allow with caution)
force_cast:
  severity: warning

# Force try (allow with caution)
force_try:
  severity: warning

# Implicitly unwrapped optional
implicitly_unwrapped_optional:
  mode: all
  severity: warning

# Multiline arguments
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# File header
file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  TTRPGCharacterSheets
    \/\/

# Reporter type
reporter: "xcode"

# SwiftLint version requirement
swiftlint_version: 0.57.0

# Custom rules
custom_rules:
  # Ensure MARK comments are properly formatted
  mark_formatting:
    name: "MARK Formatting"
    regex: '\/\/\s*MARK:(?!\s*-\s)'
    message: "MARK comments should follow format: // MARK: - Description"
    severity: warning

  # Discourage print statements in production code
  no_print_in_production:
    name: "No Print Statements"
    regex: 'print\('
    match_kinds:
      - identifier
    message: "Use proper logging instead of print() in production code"
    severity: warning
    excluded: ".*Tests\\.swift"

  # Ensure TODO/FIXME comments have issue references
  todo_with_issue:
    name: "TODO with Issue Reference"
    regex: '\/\/\s*(TODO|FIXME)(?!.*#\d+)'
    message: "TODO/FIXME comments should reference a GitHub issue: // TODO: #123 Description"
    severity: warning
